repos:
  - repo: local
    hooks:
      - id: black
        name: "Black: Checking code style"
        entry: black
        language: system
        types: [python]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format